# Generated by Django 3.1.2 on 2021-07-24 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 19, 1, 20, 103693, tzinfo=utc)),
        ),
    ]
