# Generated by Django 3.1.6 on 2021-02-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20210218_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='annoucements',
        ),
        migrations.AddField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.workspace'),
            preserve_default=False,
        ),
    ]
