# Generated by Django 3.1.2 on 2021-03-01 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20210301_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 21, 10, 32, 443760, tzinfo=utc)),
        ),
    ]
