# Generated by Django 3.1.2 on 2021-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_announcement_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
