# Generated by Django 3.1.2 on 2021-03-13 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20210313_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nn',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 21, 50, 30, 319983, tzinfo=utc)),
        ),
    ]
