# Generated by Django 3.1.2 on 2021-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20210220_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
