# Generated by Django 3.1.2 on 2021-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20210222_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
