# Generated by Django 3.1.2 on 2021-02-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20210222_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
    ]
