# Generated by Django 3.1.2 on 2021-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_remove_announcement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
