# Generated by Django 3.1.2 on 2021-02-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20210226_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, default='defaulst.png', null=True, upload_to=''),
        ),
    ]
