# Generated by Django 3.1.2 on 2021-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210218_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
